version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
         name: install dependencies and environement
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
      - run:
         name: Test with pytest
         command: |
           . venv/bin/activate
           pytest
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${f9fb539d-72ab-4659-95cd-1cd43d011500} heroku container:login
            HEROKU_API_KEY=${f9fb539d-72ab-4659-95cd-1cd43d011500} heroku container:push -a python-django-starter web
            HEROKU_API_KEY=${f9fb539d-72ab-4659-95cd-1cd43d011500} heroku container:release -a python-django-starter web

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-dev:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

