version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: pytest
workflows:
  main:
    jobs:
      - build-and-test
