version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
        name: install dependencies
        command: pip install --user -r requirements.txt
      - run:
          name: Test with pytest
          command: pytest
workflows:
  main:
    jobs:
      - build-and-test
