version: 2.1
jobs:
  run_tests:
    docker:
      - image : circleci/python:3.8
    steps:
      - checkout
      - run:
          name : install python dependencies
          commande : |
            pip install -r requirements.txt
      - run:
          name : test with pytest
          commande: |
            pytest

workflows:
  main:
    jobs:
      - run_tests
